services:
#   # Api Gateway
#   api-gateway:
#     container_name: booking-api-gateway
#     build:
#       context: .
#       dockerfile: ./services/ApiGateway/Dockerfile
#     ports:
#       - "5000:80"
#     env_file:
#       - .env.docker
#     networks:
#       - booking-network
#     depends_on:
#       identity-api:
#         condition: service_healthy

  # Identity Service API
  # identity-api:
  #   container_name: booking-identity-api
  #   build:
  #     context: .
  #     dockerfile: ./services/IdentityService/Dockerfile
  #   ports:
  #     - "5194:8080"
  #   env_file:
  #     -  .env.docker
  #   networks:
  #     - booking-network
  #   depends_on:
  #     identity-db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s

  # PostgreSQL Database
  identity-db:
    image: postgres:16-alpine
    container_name: booking-identity-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=identitydb
    networks:
      - booking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trung -d identitydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  property-db:
    image: postgres:16-alpine
    container_name: booking-property-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=propertydb
    networks:
      - booking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trung -d propertydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      
  orchestrator-db:
    image: postgres:16-alpine
    container_name: booking-orchestrator-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=orchestratordb
    networks:
      - booking-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U trung -d orchestratordb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: booking-redis
    ports:
      - "6379:6379"
    networks:
      - booking-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes

  # Seq for logging
  seq:
    image: datalust/seq:latest
    container_name: booking-seq
    ports:
      - "5341:80"
      - "5342:5341"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - booking-network
    
  # rabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: booking-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - booking-network

networks:
  booking-network:
    driver: bridge

volumes:
  identity-data:
    driver: local