services:
  # PostgreSQL - Identity
  identity-db:
    image: postgres:16-alpine
    container_name: booking-identity-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=identitydb
    networks:
      - booking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trung -d identitydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - identity-data:/var/lib/postgresql/data

  # PostgreSQL - Property
  property-db:
    image: postgres:16-alpine
    container_name: booking-property-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=propertydb
    networks:
      - booking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trung -d propertydb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - property-data:/var/lib/postgresql/data

  # PostgreSQL - Orchestrator
  orchestrator-db:
    image: postgres:16-alpine
    container_name: booking-orchestrator-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=trung
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=orchestratordb
    networks:
      - booking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trung -d orchestratordb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - orchestrator-data:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:7-alpine
    container_name: booking-redis
    ports:
      - "6379:6379"
    networks:
      - booking-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes

  # Seq
  seq:
    image: datalust/seq:latest
    container_name: booking-seq
    ports:
      - "5341:80"
      - "5342:5341"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - booking-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: booking-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - booking-network

networks:
  booking-network:
    driver: bridge

volumes:
  identity-data:
    driver: local
  property-data:
    driver: local
  orchestrator-data:
    driver: local
