// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Property.Infrastructure.DbHelper;

#nullable disable

namespace Property.Infrastructure.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    [Migration("20250625120511_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<int>("HostId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.PropertyAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyAmenities", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AmenityAggregate.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmenityGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Amenities", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AmenityAggregate.AmenityGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AmenityGroups", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.BedroomAggregate.Bedroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CotQuantity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RentalUnitId")
                        .HasColumnType("integer");

                    b.Property<bool>("SmokeAllowed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RentalUnitId");

                    b.ToTable("Bedrooms", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.ImageAggregate.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BathroomsCount")
                        .HasColumnType("integer")
                        .HasColumnName("BathroomsCount");

                    b.Property<int>("BedroomsCount")
                        .HasColumnType("integer")
                        .HasColumnName("BedroomsCount");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("MaxAdults")
                        .HasColumnType("integer");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("RentalType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("SharedBathroom")
                        .HasColumnType("boolean")
                        .HasColumnName("SharedBathroom");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("Size");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("RentalUnits", (string)null);

                    b.HasDiscriminator<string>("RentalType").HasValue("RentalUnit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnitAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer");

                    b.Property<int>("RentalUnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RentalUnitId");

                    b.ToTable("RentalUnitAmenities", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.EntirePropertyRentalUnit", b =>
                {
                    b.HasBaseType("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit");

                    b.HasDiscriminator().HasValue("EntireProperty");
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RoomRentalUnit", b =>
                {
                    b.HasBaseType("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit");

                    b.HasDiscriminator().HasValue("RoomBased");
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.Property", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.AggregateRoot.PropertyType", "Type")
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Property.Domain.ValueObjects.HouseRule", "Rules", b1 =>
                        {
                            b1.Property<int>("PropertyId")
                                .HasColumnType("integer");

                            b1.Property<int>("AgeRestriction")
                                .HasColumnType("integer");

                            b1.Property<TimeSpan>("CheckInTimeFrom")
                                .HasColumnType("interval");

                            b1.Property<TimeSpan>("CheckInTimeUntil")
                                .HasColumnType("interval");

                            b1.Property<TimeSpan>("CheckOutTimeUntil")
                                .HasColumnType("interval");

                            b1.Property<int>("FloorNumber")
                                .HasColumnType("integer");

                            b1.Property<bool>("PartyAllowed")
                                .HasColumnType("boolean");

                            b1.Property<bool>("PetAllowed")
                                .HasColumnType("boolean");

                            b1.Property<bool>("SmokingAllowed")
                                .HasColumnType("boolean");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("Property.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<int>("PropertyId")
                                .HasColumnType("integer");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Rules")
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.PropertyAmenity", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.AggregateRoot.Property", null)
                        .WithMany("Amenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AmenityAggregate.Amenity", b =>
                {
                    b.OwnsOne("Property.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<int>("AmenityId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("AmenityId");

                            b1.ToTable("Amenities");

                            b1.WithOwner()
                                .HasForeignKey("AmenityId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.BedroomAggregate.Bedroom", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", null)
                        .WithMany("Bedrooms")
                        .HasForeignKey("RentalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Property.Domain.ValueObjects.Price", "CotPrice", b1 =>
                        {
                            b1.Property<int>("BedroomId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BedroomId");

                            b1.ToTable("Bedrooms");

                            b1.WithOwner()
                                .HasForeignKey("BedroomId");
                        });

                    b.OwnsOne("Property.Domain.ValueObjects.BedType", "Type", b1 =>
                        {
                            b1.Property<int>("BedroomId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Type");

                            b1.HasKey("BedroomId");

                            b1.ToTable("Bedrooms");

                            b1.WithOwner()
                                .HasForeignKey("BedroomId");
                        });

                    b.Navigation("CotPrice")
                        .IsRequired();

                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.ImageAggregate.Image", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.AggregateRoot.Property", null)
                        .WithMany("Images")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", null)
                        .WithMany("Images")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.AggregateRoot.Property", null)
                        .WithMany("RentalUnits")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Property.Domain.ValueObjects.Price", "BasePricePerNight", b1 =>
                        {
                            b1.Property<int>("RentalUnitId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RentalUnitId");

                            b1.ToTable("RentalUnits");

                            b1.WithOwner()
                                .HasForeignKey("RentalUnitId");
                        });

                    b.Navigation("BasePricePerNight")
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnitAmenity", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", null)
                        .WithMany("Amenities")
                        .HasForeignKey("RentalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.Property", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Images");

                    b.Navigation("RentalUnits");
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Bedrooms");

                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
