// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Property.Infrastructure.DbHelper;

#nullable disable

namespace Property.Infrastructure.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    partial class PropertyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<int>("HostId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NeighborhoodDescription")
                        .HasColumnType("text");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.PropertyAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyAmenities", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.PropertyLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyLanguages", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsRoomBased")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PropertyTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Furnished and self-catering accommodation available for short- and long-term rental",
                            IsRoomBased = false,
                            Name = "Apartment"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Free-standing home with private, external entrance and rented specifically for holidays",
                            IsRoomBased = false,
                            Name = "Holiday home"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Private self-standing and self-catering home with luxury feel",
                            IsRoomBased = false,
                            Name = "Villa"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Free-standing home characterised by sloped roof and rented specifically for holidays",
                            IsRoomBased = false,
                            Name = "Chalet"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Private self-catering residences located on a shared grounds with shared facilities or recreational activities",
                            IsRoomBased = false,
                            Name = "Holiday park"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A self-catering apartment with some hotel facilities like a reception desk",
                            IsRoomBased = false,
                            Name = "Aparthotel"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Accommodation for travellers often offering restaurants, meeting rooms and other guest services",
                            IsRoomBased = true,
                            Name = "Hotel"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Private home with separate living facilities for host and guest",
                            IsRoomBased = true,
                            Name = "Guest house"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Private home offering overnight stays and breakfast",
                            IsRoomBased = true,
                            Name = "Bed and breakfast"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Private home with shared living facilities for host and guest",
                            IsRoomBased = true,
                            Name = "Homestay"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Budget accommodation with mostly dorm-style bedding and a social atmosphere",
                            IsRoomBased = true,
                            Name = "Hostel"
                        },
                        new
                        {
                            Id = 13,
                            Description = "A self-catering apartment with some hotel facilities like a reception desk",
                            IsRoomBased = true,
                            Name = "Aparthotel"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Extremely small units or capsules offering cheap and basic overnight accommodation",
                            IsRoomBased = true,
                            Name = "Capsule hotel"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Private home with simple accommodation in the countryside",
                            IsRoomBased = true,
                            Name = "Country house"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Private farm with simple accommodation",
                            IsRoomBased = true,
                            Name = "Farm stay"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Small and basic accommodation with a rustic feel",
                            IsRoomBased = true,
                            Name = "Inn"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Adult-only accommodation rented per hour or night",
                            IsRoomBased = true,
                            Name = "Love hotel"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Roadside hotel usually for motorists, with direct access to parking and little to no amenities",
                            IsRoomBased = true,
                            Name = "Motel"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Traditional Moroccan accommodation with a courtyard and luxury feel",
                            IsRoomBased = true,
                            Name = "Riad"
                        },
                        new
                        {
                            Id = 21,
                            Description = "A place for relaxation with onsite restaurants, activities and often with a luxury feel",
                            IsRoomBased = true,
                            Name = "Resort"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Traditional Japanese-style accommodation with meal options",
                            IsRoomBased = true,
                            Name = "Ryokan"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Private home with accommodation surrounded by nature, such as mountains or forest",
                            IsRoomBased = true,
                            Name = "Lodge"
                        });
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AmenityAggregate.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AmenityGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Amenities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPaid = false,
                            Name = "Air conditioning"
                        },
                        new
                        {
                            Id = 2,
                            IsPaid = false,
                            Name = "Heating"
                        },
                        new
                        {
                            Id = 3,
                            IsPaid = false,
                            Name = "Free Wifi"
                        },
                        new
                        {
                            Id = 4,
                            IsPaid = false,
                            Name = "Electric vehicle charing station"
                        },
                        new
                        {
                            Id = 5,
                            IsPaid = false,
                            Name = "Free parking on premises"
                        });
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AmenityAggregate.AmenityGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AmenityGroups", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.BedroomAggregate.Bedroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoubleBeds")
                        .HasColumnType("integer");

                    b.Property<int>("KingBeds")
                        .HasColumnType("integer");

                    b.Property<int>("RentalUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("SingleBeds")
                        .HasColumnType("integer");

                    b.Property<int>("SofaBeds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RentalUnitId");

                    b.ToTable("Bedrooms", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.ImageAggregate.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.LanguageAggregate.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Name = "French"
                        },
                        new
                        {
                            Id = 3,
                            Name = "German"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Korean"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Russian"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Arabic"
                        });
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BathroomsCount")
                        .HasColumnType("integer")
                        .HasColumnName("BathroomsCount");

                    b.Property<int>("BedroomsCount")
                        .HasColumnType("integer")
                        .HasColumnName("BedroomsCount");

                    b.Property<int>("MaxAdults")
                        .HasColumnType("integer");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("integer");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("RentalType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<bool>("SharedBathroom")
                        .HasColumnType("boolean")
                        .HasColumnName("SharedBathroom");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("Size");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("RentalUnits", null, t =>
                        {
                            t.Property("RentalType")
                                .HasColumnName("RentalUnit_RentalType");
                        });

                    b.HasDiscriminator<string>("RentalType").HasValue("RentalUnit");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnitAmenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AmenityId")
                        .HasColumnType("integer");

                    b.Property<int>("RentalUnitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RentalUnitId");

                    b.ToTable("RentalUnitAmenities", (string)null);
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.EntirePropertyRentalUnit", b =>
                {
                    b.HasBaseType("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit");

                    b.ToTable("RentalUnits", t =>
                        {
                            t.Property("RentalType")
                                .HasColumnName("RentalUnit_RentalType");
                        });

                    b.HasDiscriminator().HasValue("EntireProperty");
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RoomRentalUnit", b =>
                {
                    b.HasBaseType("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.ToTable("RentalUnits", t =>
                        {
                            t.Property("RentalType")
                                .HasColumnName("RentalUnit_RentalType");
                        });

                    b.HasDiscriminator().HasValue("RoomBased");
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.Property", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.AggregateRoot.PropertyType", "Type")
                        .WithMany()
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Property.Domain.ValueObjects.HouseRule", "Rules", b1 =>
                        {
                            b1.Property<int>("PropertyId")
                                .HasColumnType("integer");

                            b1.Property<int>("AgeRestriction")
                                .HasColumnType("integer")
                                .HasColumnName("AgeRestriction");

                            b1.Property<TimeSpan>("CheckInTimeFrom")
                                .HasColumnType("interval")
                                .HasColumnName("CheckInTimeFrom");

                            b1.Property<TimeSpan>("CheckInTimeUntil")
                                .HasColumnType("interval")
                                .HasColumnName("CheckInTimeUntil");

                            b1.Property<TimeSpan>("CheckOutTimeUntil")
                                .HasColumnType("interval")
                                .HasColumnName("CheckOutTimeUntil");

                            b1.Property<bool>("PartyAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("PartyAllowed");

                            b1.Property<bool>("PetAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("PetAllowed");

                            b1.Property<bool>("SmokingAllowed")
                                .HasColumnType("boolean")
                                .HasColumnName("SmokingAllowed");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("Property.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<int>("PropertyId")
                                .HasColumnType("integer");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Address");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Country");

                            b1.Property<int>("PostCode")
                                .HasColumnType("integer")
                                .HasColumnName("PostCode");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.Navigation("Location");

                    b.Navigation("Rules");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.PropertyAmenity", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.AggregateRoot.Property", null)
                        .WithMany("Amenities")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Property.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<int>("PropertyAmenityId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Currency");

                            b1.HasKey("PropertyAmenityId");

                            b1.ToTable("PropertyAmenities");

                            b1.WithOwner()
                                .HasForeignKey("PropertyAmenityId");
                        });

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.PropertyLanguage", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.AggregateRoot.Property", null)
                        .WithMany("Languages")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.BedroomAggregate.Bedroom", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", null)
                        .WithMany("Bedrooms")
                        .HasForeignKey("RentalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.ImageAggregate.Image", b =>
                {
                    b.OwnsOne("Property.Domain.ValueObjects.EntityType", "EntityType", b1 =>
                        {
                            b1.Property<int>("ImageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("EntityType");

                            b1.HasKey("ImageId");

                            b1.ToTable("Images");

                            b1.WithOwner()
                                .HasForeignKey("ImageId");
                        });

                    b.Navigation("EntityType")
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.AggregateRoot.Property", null)
                        .WithMany("RentalUnits")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Property.Domain.ValueObjects.Price", "BasePricePerNight", b1 =>
                        {
                            b1.Property<int>("RentalUnitId")
                                .HasColumnType("integer");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric")
                                .HasColumnName("BasePricePerNight");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("RentalUnitId");

                            b1.ToTable("RentalUnits");

                            b1.WithOwner()
                                .HasForeignKey("RentalUnitId");
                        });

                    b.OwnsOne("Property.Domain.ValueObjects.RentalUnitType", "Type", b1 =>
                        {
                            b1.Property<int>("RentalUnitId")
                                .HasColumnType("integer");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RentalType");

                            b1.HasKey("RentalUnitId");

                            b1.ToTable("RentalUnits");

                            b1.WithOwner()
                                .HasForeignKey("RentalUnitId");
                        });

                    b.Navigation("BasePricePerNight")
                        .IsRequired();

                    b.Navigation("Type")
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnitAmenity", b =>
                {
                    b.HasOne("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", null)
                        .WithMany("Amenities")
                        .HasForeignKey("RentalUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Property.Domain.Aggregates.AggregateRoot.Property", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Languages");

                    b.Navigation("RentalUnits");
                });

            modelBuilder.Entity("Property.Domain.Aggregates.RentalUnitAggregate.RentalUnit", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Bedrooms");
                });
#pragma warning restore 612, 618
        }
    }
}
